spring:
  profiles:
    active:
    - chaos-monkey
  
---
spring:
  profiles: chaos-monkey
chaos:
  monkey:
    enabled: true
    watcher:
      rest-controller: true
      controller: true
      component: false
      service: true
      repository: true
    assaults:
      level: 5
      latency-active: true
      latency-range-start: 1000
      latency-range-end: 3000
      exceptions-active: true
      kill-application-active: false

management:
  endpoint:
    chaosmonkey:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
        - chaosmonkey